In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [8]:
daily_engagement = pd.read_csv('daily_engagement.csv')
len(daily_engagement['acct'].unique())

1237

In [19]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

In [20]:
# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [32]:
def max_employment(countries,employment): 
    max_country = None 
    max_employment = 0 
    for i in range(len(countries)): 
        if employment[i] > max_employment: 
            max_employment = employment[i]
            max_country = countries[i]
    return(max_country,max_employment)

In [33]:
max_employment(countries,employment)

('Angola', 75.699996949999999)

In [34]:
def max_employment2(countries,employment): 
    i = employment.argmax()
    return(countries[i],employment[i])

In [35]:
max_employment2(countries,employment)

('Angola', 75.699996949999999)

In [47]:
def standardize_data(values):
    standardize = (values - values.mean())/values.std()
    return standardize

In [48]:
values = np.array([1,2,3,4,5])

In [49]:
standardize_data(values)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [39]:
values - values.mean()

array([-2., -1.,  0.,  1.,  2.])

In [40]:
values.mean() 

3.0

In [41]:
values = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
standardize_data(values)

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])